
import 'package:flutter/material.dart';

class L10n {
  static String lang = 'de'; 

  static final Map<String, Map<String, String>> _values = {
    'de': {
      'about': 'Über',
      'about_credits_text': 'Besonderer Dank geht an J0EK3R (Ivan Murvai)\nfür das Reverse Engineering des Mould King 4.0/6.0 Protokolls.',
      'about_credits_title': 'Danksagung & Credits:',
      'about_description': 'Ein freies Hobbyprojekt für Klemmbausteinfreunde.\nLizenziert unter GNU GPL v3.',
      'about_github_btn': 'Quellcode auf GitHub',
      'accessories': 'Zubehör:',
      'actual': 'IST',
      'blockade': 'Rad-Stopp',
      'brake': 'Bremse',
      'btn_connect': 'Verbinden',
      'btn_disconnect': 'Trennen',
      'btn_save': 'Speichern',
      'btn_start_scan': 'HUBS FINDEN',
      'cancel': 'Abbrechen',
      'channel_select': 'Kanal (1-3)',
      'choose_picture': 'Bild auswählen',
      'color': 'Farbe',
      'confirm_delete': 'Wirklich löschen?',
      'connect': 'VERBINDEN',
      'connecting_classic': 'Sende Handshake (Broadcast)...',
      'connection_lost': 'Verbindung verloren zu',
      'controls': 'Steuerpult',
      'delete': 'Löschen',
      'departure': 'Abfahrt',
      'design_theme': 'Design (Dark Mode)',
      'diagnosis': 'Diagnose',
      'disconnect': 'TRENNEN',
      'display_always_on': 'Display immer an',
      'display_always_on_desc': 'Display bleibt nur dauerhaft an, solange mindestens eine Lok verbunden ist.',
      'edit': 'Bearbeiten',
      'export': 'Backup Export',
      'fanfare': 'Fanfare',
      'fuel': 'Tanken',
      'global_stop': 'GLOBAL STOPP',
      'halt': 'HALT',
      'handset_connected': 'Verbunden und aktiv',
      'handset_scanning': 'Suche nach Fernbedienung...',
      'handset_disconnected': 'Nicht verbunden',
      'handset_paired_success': 'Fernbedienung erfolgreich gekoppelt!',
      'hardware_and_setup': 'Hardware & Einrichtung',
      'horn': 'Hupe',
      'import': 'Backup Import',
      'info_no_mac_needed': 'Keine MAC benötigt',
      'invert': 'Invertieren',
      'label_change_photo': 'Bild antippen zum Ändern',
      'label_choose_protocol': 'Protokoll wählen',
      'label_mac': 'MAC-Adresse',
      'label_name': 'Name der Lok',
      'label_notes': 'Notizen',
      'label_photo': 'Foto wählen',
      'label_protocol': 'Protokoll',
      'label_protocol': 'Protokoll / Hub-Typ',
      'lang_changed': 'Sprache geändert',
      'light': 'Licht',
      'light_b': 'Licht B',
      'light_c': 'Licht C',
      'list': 'Lokliste',
      'mould_king_classic': 'Mould King Classic (4.0)',
      'mould_king_classic_desc': 'Broadcast-Steuerung für ältere 4.0 Hubs (Dino)',
      'msg_incomplete': 'Bitte Protokoll auswählen und ggf. MAC eintragen!',
      'msg_scan_error': 'Scan-Fehler',
      'new_train': 'Neue Lok anlegen',
      'no_trains': 'Keine Loks vorhanden.\nNutze das \'+\' zum Anlegen.',
      'notes_header': 'INFOS & WARTUNG',
      'offline': 'GETRENNT',
      'online': 'VERBUNDEN',
      'panel_mode_gears': 'Fahrstufen',
      'panel_mode_manual': 'Manuell (+/-)',
      'panel_profile_1': 'Profil I (Solo)',
      'panel_profile_2': 'Profil II (Last)',
      'port_light': 'Licht',
      'port_motor': 'Motor',
      'port_motor_inv': 'Motor (Invertiert)',
      'port_none': 'Nichts',
      'protocol_mk_classic': 'Mould King (Classic / Broadcast)',
      'protocol_mk_modern': 'Mould King (Modern / BLE)',
      'readme': 'Anleitung',
      'readme_error': 'Fehler: readme.txt konnte nicht geladen werden.',
      'scan_not_required': 'Broadcast-Modus: Für diesen Hub ist kein Scan oder Koppeln nötig.',
      'scan_running': 'Suche läuft...',
      'select_train': 'Bitte wähle eine Lok aus der Liste aus',
      'settings': 'Einstellungen',
      'settings_title': 'Einstellungen',
      'stop': 'NOTHALT',
      'stop_all': 'NOT-AUS',
      'tab_general': 'ALLGEMEIN',
      'tab_scan': 'SCAN',
      'tab_tuning': 'FEINABSTIMMUNG',
      'take_picture': 'Foto aufnehmen',
      'target': 'SOLL',
      'template_circuit_cube': 'Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_lego_duplo': 'Einfacher Antrieb (A), Licht & Sound intern',
      'template_lego_duplo': 'Duplo-Lok, ohne Ports.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_lego_hub': 'Standard-Belegung:\n• Port A: Antrieb\n• Port B: Licht/Motor\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_mould_king': 'Standard-Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\n• Port D: evt. 2. Antrieb (invertiert)\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_mould_king_classic': 'Standard-Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\n• Port D: evt. 2. Antrieb (invertiert)\nVerbindung: Broadcast-Modus.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_mould_king_rwy_controller': 'FUNKTIONIERT NOCH NICHT\nNur Motor, kein Licht',
      'template_pybricks_hub': 'FUNKTIONIERT (NOCH) NICHT\nStandard-Belegung:\n• Port A: Antrieb\n• Port B: Licht/Motor\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'theme_dark': 'Dunkel',
      'theme_light': 'Hell',
      'theme_system': 'System',
      'tuning_acceleration': 'Beschleunigung',
      'tuning_auto_light': 'Automatisches Licht',
      'tuning_auto_light_help': 'Aktiviert das fahrtrichtungsabhängige Umpolen an Port B für BicolorLEDs',
      'tuning_brake': 'Bremskraft',
      'tuning_delta_step': 'Stufensprung (+/- Tasten)',
      'tuning_driving_behavior': 'FAHRVERHALTEN',
      'tuning_general_settings': 'Allgemeine Einstellungen',
      'tuning_invert_direction': 'Richtung invertieren',
      'tuning_invert_direction_help': 'Kehrt die Standard-Laufrichtung des Motors in der App um',
      'tuning_limits': 'Geschwindigkeitsgrenzen',
      'tuning_profile_1': 'PROFIL I (Solo-Fahrt)',
      'tuning_profile_2': 'PROFIL II (Fahrt unter Last)',
      'tuning_ramp_delay': 'Trägheit [ms]',
      'tuning_ramping': 'Beschleunigungs-Rampe',
      'tuning_reverse': 'Rückwärts-Limit',
      'tuning_speed_levels': 'FAHRSTUFEN',
      'ui_scaling': 'UI Skalierung',
      'unknown_device': 'Unbekanntes Gerät',
      'unknown_protocol': 'Unbekanntes Protokoll:',
      'vMax': 'Vmax (Höchstgeschwindigkeit)',
      'vMin': 'Vmin (Mindestgeschwindigkeit)',
      'workshop_add': 'NEUE LOK ANLEGEN',
      'workshop_edit': 'LOK EDITIEREN',
      'workshop_edit_save': 'SPEICHERN',



    },
    'en': {
      'about': 'About',
      'about_credits_text': 'Special thanks to J0EK3R (Ivan Murvai)\nfor reverse engineering the Mould King 4.0/6.0 protocol.',
      'about_credits_title': 'Credits & Acknowledgments:',
      'about_description': 'A free hobby project for brick enthusiasts.\nLicensed under GNU GPL v3.',
      'about_github_btn': 'View Source on GitHub',
      'accessories': 'Accessories:',
      'actual': 'ACTUAL',
      'blockade': 'Wheel-Stopp',
      'brake': 'Brake',
      'btn_connect': 'Connect',
      'btn_disconnect': 'Disconnect',
      'btn_save': 'Save',
      'btn_start_scan': 'FIND HUBS',
      'cancel': 'Cancel',
      'channel_select': 'Channel (1-3)',
      'choose_picture': 'Choose Picture',
      'color': 'Color',
      'confirm_delete': 'Confirm delete?',
      'connect': 'CONNECT',
      'connecting_classic': 'Sending Handshake (Broadcast)...',
      'connection_lost': 'Connection lost to',
      'controls': 'Control Panel',
      'delete': 'Delete',
      'departure': 'Departure',
      'design_theme': 'Design (Dark Mode)',
      'diagnosis': 'Diagnose',
      'disconnect': 'DISCONNECT SAFELY',
      'display_always_on': 'Keep Display On',
      'display_always_on_desc': 'Screen stays on only while at least one train is connected.',
      'edit': 'Edit',
      'export': 'Export Backup',
      'fanfare': 'Fanfare',
      'fuel': 'Fuel',
      'global_stop': 'GLOBAL STOP',
      'halt': 'HALT',
      'handset_connected': 'Connected and active',
      'handset_scanning': 'Searching for handset...',
      'handset_disconnected': 'Not connected',
      'handset_paired_success': 'Handset paired successfully',
      'hardware_and_setup': 'Hardware & Setup',
      'horn': 'Horn',
      'import': 'Import Backup',
      'info_no_mac_needed': 'No MAC needed',
      'invert': 'Invert',
      'label_change_photo': 'Tap image to change',
      'label_choose_protocol': 'Choose Protocol',
      'label_mac': 'MAC Address',
      'label_name': 'Train Name',
      'label_notes': 'Notes',
      'label_photo': 'Pick Photo',
      'label_protocol': 'Protocol',
      'label_protocol': 'Protocol / Hub Type',
      'lang_changed': 'Language changed',
      'light': 'Light',
      'light_b': 'Light B',
      'light_c': 'Light C',
      'list': 'Train List',
      'mould_king_classic': 'Mould King Classic (4.0)',
      'mould_king_classic_desc': 'Broadcast control for older 4.0 hubs (Dino)',
      'msg_incomplete': 'Please select protocol and enter MAC address if necessary!',
      'msg_scan_error': 'Scan error',
      'new_train': 'Add New Train',
      'no_trains': 'No trains available.\nUse \'+\' to create one.',
      'notes_header': 'INFO & MAINTENANCE',
      'offline': 'OFFLINE',
      'online': 'ONLINE',
      'panel_mode_gears': 'Gears',
      'panel_mode_manual': 'Manual (+/-)',
      'panel_profile_1': 'Profile I (Solo)',
      'panel_profile_2': 'Profile II (Load)',
      'port_light': 'Light',
      'port_motor': 'Motor',
      'port_motor_inv': 'Motor (Inverted)',
      'port_none': 'None',
      'protocol_mk_classic': 'Mould King (Classic / Broadcast)',
      'protocol_mk_modern': 'Mould King (Modern / BLE)',
      'readme': 'Manual',
      'scan_not_required': 'Broadcast Mode: No scan or pairing required for this hub.',
      'scan_running': 'Scanning...',
      'select_train': 'Please select a train from the list',
      'settings': 'Settings',
      'settings_title': 'Settings',
      'stop': 'STOP',
      'stop_all': 'Emergency Stop',
      'tab_general': 'GENERAL',
      'tab_scan': 'SCAN',
      'tab_tuning': 'TUNING',
      'take_picture': 'Take Picture',
      'target': 'TARGET',
      'template_circuit_cube': 'Assignment:\n• Port A: Drive\n• Port B/C: Light (Auto-Light)\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_lego_duplo': 'Simple drive (A), internal light & sound',
      'template_lego_hub': 'Standard Assignment:\n• Port A: Drive\n• Port B: Light/Drive\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_mould_king': 'Standard Assignment:\n• Port A: Drive\n• Port B/C: Light (Auto-Light)\n• Port D: poss. 2nd Drive (inverted)\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_mould_king_classic': 'Standard Assignment:\n• Port A: Drive\n• Port B/C: Licht (Auto-Light)\n• Port D: evt. 2. Antrieb (invertiert)\nConnection: Broadcast.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_mould_king_rwy_controller': 'CURRENTLY NOT WORKING\nOnly motor, no light',
      'template_pybricks_hub': 'CURRENTLY NOT WORKING\nStandard Assignment:\n• Port A: Drive\n• Port B: Light/Drive\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'theme_dark': 'dark',
      'theme_light': 'light',
      'theme_system': 'System',
      'tuning_acceleration': 'Acceleration',
      'tuning_auto_light': 'Automatic Light',
      'tuning_auto_light_help': 'Activates the direction-dependent polarity reversal at Port B for bicolor LEDs',
      'tuning_brake': 'Braking Force',
      'tuning_delta_step': 'Step Size (+/- Buttons)',
      'tuning_driving_behavior': 'DRIVING BEHAVIOR',
      'tuning_general_settings': 'General Settings',
      'tuning_invert_direction': 'Invert direction',
      'tuning_invert_direction_help': 'Reverses the direction e.g., of a steam locomotive',
      'tuning_limits': 'Speed Limits',
      'tuning_profile_1': 'PROFILE I (Solo-Drive)',
      'tuning_profile_2': 'PROFILE II (Under Load)',
      'tuning_ramp_delay': 'Inertia [ms]',
      'tuning_ramping': 'Acceleration Ramp',
      'tuning_reverse': 'Max Reverse Limit',
      'tuning_speed_levels': 'Speed Levels (Presets)',
      'ui_scaling': 'UI Scaling',
      'unknown_device': 'Unknown Device',
      'unknown_protocol': 'Unknown Protocol:',
      'vMax': 'Vmax (Maximum Speed)',
      'vMin': 'Vmin (Minimum Speed)',
      'workshop_add': 'ADD NEW TRAIN',
      'workshop_edit': 'EDIT TRAIN',
      'workshop_edit_save': 'Save',

    }
  };

  static String tr(String key) {
    return _values[lang]?[key] ?? key;
  }
}

extension Loc on String {
  String get tr => L10n.tr(this);
}