
import 'package:flutter/material.dart';

class L10n {
  static String lang = 'de'; 

  static final Map<String, Map<String, String>> _values = {
    'de': {
      'connect': 'VERBINDEN',
      'connection_lost': 'Verbindung verloren zu',
      'disconnect': 'TRENNEN',
      "display_always_on_desc": "Display bleibt nur dauerhaft an, solange mindestens eine Lok verbunden ist.",
      'diagnosis' : 'Diagnose',
      'global_stop': 'GLOBAL STOPP',
      'new_train': 'Neue Lok anlegen',
      'no_trains': 'Keine Loks vorhanden.\nNutze das \'+\' zum Anlegen.',
      'select_train': 'Bitte wähle eine Lok aus der Liste aus',
      'halt': 'HALT',
      'stop': 'NOTHALT',
      'notes_header': 'INFOS & WARTUNG',
      'accessories': 'Zubehör:',
      'invert': 'Invertieren',
      'export': 'Backup Export',
      'import': 'Backup Import',
      'settings': 'Einstellungen',
      'readme': 'Anleitung',
      'about': 'Über',
      'online': 'VERBUNDEN',
      'offline': 'GETRENNT',
      'edit': 'Bearbeiten',
      'delete': 'Löschen',
      'cancel': 'Abbrechen',
      'confirm_delete': 'Wirklich löschen?',
      'workshop_add': 'NEUE LOK ANLEGEN',
      'workshop_edit': 'SPEICHERN',
      'tab_general': 'ALLGEMEIN',
      'tab_scan': 'SCAN',
      'tab_tuning': 'FEINABSTIMMUNG',
      'label_name': 'Name der Lok',
      'label_mac': 'MAC-Adresse',
      'label_protocol': 'Protokoll / Hub-Typ',
      'label_notes': 'Notizen',
      'label_photo': 'Foto wählen',
      'label_change_photo': 'Bild antippen zum Ändern',
      'btn_save': 'Speichern',
      'btn_start_scan': 'HUBS FINDEN',
      'scan_running': 'Suche läuft...',
      'tuning_reverse': 'Rückwärts-Limit',
      'tuning_ramping': 'Beschleunigungs-Rampe',
      'tuning_auto_light': 'Automatisches Licht',
      'tuning_speed_levels': 'GESCHWINDIGKEITSSTUFEN (%)',
      'tuning_driving_behavior': 'FAHRVERHALTEN',
      'msg_incomplete': 'Bitte Protokoll auswählen und ggf. MAC eintragen!',
      'msg_scan_error': 'Scan-Fehler',
      'settings_title': 'Einstellungen',
      'ui_scaling': 'UI Skalierung',
      'display_always_on': 'Display immer an',
      'design_theme': 'Design (Dark Mode)',
      'theme_system': 'System',
      'theme_light': 'Hell',
      'theme_dark': 'Dunkel',
      'lang_changed': 'Sprache geändert',
      'light_b': 'Licht B',
      'light_c': 'Licht C',
      'label_choose_protocol': 'Protokoll wählen',
      'protocol_mk_modern': 'Mould King (Modern / BLE)',
      'protocol_mk_classic': 'Mould King (Classic / Broadcast)',
      'unknown_device': 'Unbekanntes Gerät',
      'port_motor': 'Motor',
      'port_motor_inv': 'Motor (Invertiert)',
      'port_light': 'Licht',
      'port_none': 'Nichts',
      'label_protocol': 'Protokoll',
      'template_lego_hub': "Standard-Belegung:\n• Port A: Antrieb\n• Port B: Licht/Motor\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten",
      'template_lego_duplo': "Duplo-Lok, ohne Ports.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten",
      'template_pybricks_hub': "Standard-Belegung:\n• Port A: Antrieb\n• Port B: Licht/Motor\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten",
      'template_mould_king': "Standard-Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\n• Port D: evt. 2. Antrieb (invertiert)\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten",
      'template_mould_king_classic': "Standard-Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\n• Port D: evt. 2. Antrieb (invertiert)\nVerbindung: Broadcast-Modus.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten",
      'template_mould_king_rwy_controller': 'FUNKTIONIERT NOCH NICHT\nNur Motor, kein Licht',
      'template_circuit_cube': "Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten",
      'mould_king_classic': 'Mould King Classic (4.0)',
      'mould_king_classic_desc': 'Broadcast-Steuerung für ältere 4.0 Hubs (Dino)',
      'connecting_classic': 'Sende Handshake (Broadcast)...',
      'about_description': 'Ein freies Hobbyprojekt für Klemmbausteinfreunde.\nLizenziert unter GNU GPL v3.',
      'about_credits_title': 'Danksagung & Credits:',
      'about_credits_text': 'Besonderer Dank geht an J0EK3R (Ivan Murvai)\nfür das Reverse Engineering des Mould King 4.0/6.0 Protokolls.',
      'about_github_btn': 'Quellcode auf GitHub',
      'scan_not_required': 'Broadcast-Modus: Für diesen Hub ist kein Scan oder Koppeln nötig.',
      'info_no_mac_needed': 'Keine MAC benötigt',
      'list': 'Lokliste',
      'controls': 'Steuerpult',
      'stop_all': 'NOT-AUS',
      'template_lego_duplo': 'Einfacher Antrieb (A), Licht & Sound intern',
      'horn': 'Hupe',
      'fuel': 'Tanken',
      'fanfare': 'Fanfare',
      'light': 'Licht',
      'blockade': 'Rad-Stopp',
      'color': 'Farbe',
      'departure': 'Abfahrt',
      'brake': 'Bremse',
      'readme_error': 'Fehler: readme.txt konnte nicht geladen werden.',
      'readme': 'Anleitung',
      'take_picture': 'Foto aufnehmen',
      'choose_picture': 'Bild auswählen',
      'panel_profile_1': "Profil I (Solo)",
      'panel_profile_2': "Profil II (Last)",
      'panel_mode_manual': "Manuell (+/-)",
      'panel_mode_gears': "Fahrstufen",
      'tuning_profile_1': "PROFIL I (Solo-Fahrt)",
      'tuning_profile_2': "PROFIL II (Fahrt unter Last)",
      'tuning_acceleration': "Beschleunigung",
      'tuning_brake': "Bremskraft",
      'tuning_ramp_delay': "Trägheit [ms]",
      'tuning_general_settings': "Allgemeine Einstellungen",
      'tuning_delta_step': "Stufensprung (+/- Tasten)",
      'actual': "IST",
      'target': "SOLL",
      'unknown_protocol': "Unbekanntes Protokoll:",
      'tuning_invert_direction': 'Richtung invertieren',
      'tuning_invert_direction_help': 'Kehrt die Standard-Laufrichtung des Motors in der App um',
      'tuning_auto_light_help': 'Aktiviert das fahrtrichtungsabhängige Umpolen an Port B für BicolorLEDs',




    },
    'en': {
      'connect': 'CONNECT',
      'connection_lost': 'Connection lost to',
      'disconnect': 'DISCONNECT SAFELY',
      "display_always_on_desc": "Screen stays on only while at least one train is connected.",
      'diagnosis' : 'Diagnose',
      'global_stop': 'GLOBAL STOP',
      'new_train': 'Add New Train',
      'no_trains': 'No trains available.\nUse \'+\' to create one.',
      'select_train': 'Please select a train from the list',
      'halt': 'HALT',
      'stop': 'STOP',
      'notes_header': 'INFO & MAINTENANCE',
      'accessories': 'Accessories:',
      'invert': 'Invert',
      'export': 'Export Backup',
      'import': 'Import Backup',
      'settings': 'Settings',
      'readme': 'Manual',
      'about': 'About',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'edit': 'Edit',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'confirm_delete': 'Confirm delete?',
      'workshop_add': 'ADD NEW TRAIN',
      'workshop_edit': 'Save',
      'tab_general': 'GENERAL',
      'tab_scan': 'SCAN',
      'tab_tuning': 'TUNING',
      'label_name': 'Train Name',
      'label_mac': 'MAC Address',
      'label_protocol': 'Protocol / Hub Type',
      'label_notes': 'Notes',
      'label_photo': 'Pick Photo',
      'label_change_photo': 'Tap image to change',
      'btn_save': 'Save',
      'btn_start_scan': 'FIND HUBS',
      'scan_running': 'Scanning...',
      'tuning_reverse': 'Max Reverse Limit',
      'tuning_ramping': 'Acceleration Ramp',
      'tuning_auto_light': 'Automatic Light',
      'tuning_speed_levels': 'SPEED LEVELS (%)',
      'tuning_driving_behavior': 'DRIVING BEHAVIOR',
      'msg_incomplete': 'Please select protocol and enter MAC address if necessary!',
      'msg_scan_error': 'Scan error',
      'settings_title': 'Settings',
      'ui_scaling': 'UI Scaling',
      'display_always_on': 'Keep Display On',
      'design_theme': 'Design (Dark Mode)',
      'theme_system': 'System',
      'theme_light': 'light',
      'theme_dark': 'dark',
      'lang_changed': 'Language changed',
      'light_b': 'Light B',
      'light_c': 'Light C',
      'label_choose_protocol': 'Choose Protocol',
      'protocol_mk_modern': 'Mould King (Modern / BLE)',
      'protocol_mk_classic': 'Mould King (Classic / Broadcast)',
      'unknown_device': 'Unknown Device',
      'port_motor': 'Motor',
      'port_motor_inv': 'Motor (Inverted)',
      'port_light': 'Light',
      'port_none': 'None',
      'label_protocol': 'Protocol', 
      'template_lego_hub': "Standard Assignment:\n• Port A: Drive\n• Port B: Light/Drive\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.",
      'template_pybricks_hub': "Standard Assignment:\n• Port A: Drive\n• Port B: Light/Drive\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.",
      'template_mould_king': "Standard Assignment:\n• Port A: Drive\n• Port B/C: Light (Auto-Light)\n• Port D: poss. 2nd Drive (inverted)\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.",
      'template_mould_king_classic': "Standard Assignment:\n• Port A: Drive\n• Port B/C: Licht (Auto-Light)\n• Port D: evt. 2. Antrieb (invertiert)\nConnection: Broadcast.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.",
      'template_mould_king_rwy_controller': 'CURRENTLY NOT WORKING\nOnly motor, no light',
      'template_circuit_cube': "Assignment:\n• Port A: Drive\n• Port B/C: Light (Auto-Light)\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.",
      'mould_king_classic': 'Mould King Classic (4.0)',
      'mould_king_classic_desc': 'Broadcast control for older 4.0 hubs (Dino)',
      'connecting_classic': 'Sending Handshake (Broadcast)...',
      'about_description': 'A free hobby project for brick enthusiasts.\nLicensed under GNU GPL v3.',
      'about_credits_title': 'Credits & Acknowledgments:',
      'about_credits_text': 'Special thanks to J0EK3R (Ivan Murvai)\nfor reverse engineering the Mould King 4.0/6.0 protocol.',
      'about_github_btn': 'View Source on GitHub',
      'scan_not_required': 'Broadcast Mode: No scan or pairing required for this hub.',
      'info_no_mac_needed': 'No MAC needed',
      'list': 'Train List',
      'controls': 'Control Panel',
      'stop_all': 'Emergency Stop',
      'template_lego_duplo': 'Simple drive (A), internal light & sound',
      'horn': 'Horn',
      'fuel': 'Fuel',
      'fanfare': 'Fanfare',
      'light': 'Light',
      'blockade': 'Wheel-Stopp',
      'color': 'Color',
      'departure': 'Departure',
      'brake': 'Brake',
      'take_picture': 'Take Picture',
      'choose_picture': 'Choose Picture',
      
      'panel_profile_1': "Profile I (Solo)",
      'panel_profile_2': "Profile II (Load)",
      'panel_mode_manual': "Manual (+/-)",
      'panel_mode_gears': "Gears",
      'tuning_profile_1': "PROFILE I (Solo-Drive)",
      'tuning_profile_2': "PROFILE II (Under Load)",
      'tuning_acceleration': "Acceleration",
      'tuning_brake': "Braking Force",
      'tuning_ramp_delay': "Inertia [ms]",
      'tuning_general_settings': "General Settings",
      'tuning_delta_step': "Step Size (+/- Buttons)",
      'actual': "ACTUAL",
      'target': "TARGET",
      'unknown_protocol': "Unknown Protocol:",
      'tuning_invert_direction': 'Invert direction',
      'tuning_invert_direction_help': 'Reverses the direction e.g., of a steam locomotive',
      'tuning_auto_light_help': 'Activates the direction-dependent polarity reversal at Port B for bicolor LEDs',


    }
  };

  static String tr(String key) {
    return _values[lang]?[key] ?? key;
  }
}

extension Loc on String {
  String get tr => L10n.tr(this);
}