
import 'package:flutter/material.dart';

class L10n {
  static String lang = 'de'; 

  static final Map<String, Map<String, String>> _values = {
    'de': {
      'about': 'Über',
      'about_credits_text': 'Besonderer Dank geht an J0EK3R (Ivan Murvai)\nfür das Reverse Engineering des Mould King 4.0/6.0 Protokolls.',
      'about_credits_title': 'Danksagung & Credits:',
      'about_description': 'Ein freies Hobbyprojekt für Klemmbausteinfreunde.\n\n'
                           'Lizenziert unter GNU GPL v3.\n\n'
                           'Es besteht keine Verbindung zu den genannten Herstellern. Sämtliche Markennamen dienen ausschließlich der Beschreibung der technischen Kompatibilität und Interoperabilität.\n\n'
                           'Die Bereitstellung erfolgt „wie besehen“ (as-is) ohne jegliche Gewährleistung oder Haftung für Schäden an der verwendeten Hardware (z. B. Hubs, Motoren, Fernbedienungen).',      
      'about_github_btn': 'Quellcode auf GitHub',
      'accessories': 'Zubehör:',
      'actual': 'IST',
      'add': 'Hinzufügen',
      'add_new_button': 'Neuen Knopf hinzufügen',
      'blockade': 'Rad-Stopp',
      'brake': 'Bremse',
      'btn_connect': 'Verbinden',
      'btn_disconnect': 'Trennen',
      'btn_save': 'Speichern',
      'btn_start_scan': 'HUBS FINDEN',
      'buwizz_power_title': 'BuWizz Leistungsmodus',
      'buwizz_power_subtitle': 'Wird erst mit neuer Verbindung wirksam.\nAchtung: Höhere Spannungen auf eigene Gefahr nutzen!',
      'buwizz_power_slow': 'Slow (ca. 5,2V)',
      'buwizz_power_normal': 'Normal (ca. 7,2V - Standard)',
      'buwizz_power_fast': 'Fast (ca. 9,2V)',
      'buwizz_power_ludicrous': 'Ludicrous (ca. 11,2V)',
      'buwizz_power_warning': 'Erhöhte Spannung kann Überhitzung führen und Standard-Motoren zerstören.',
      'cancel': 'Abbrechen',
      'channel': 'Kanal',
      'choose_picture': 'Bild auswählen',
      'color': 'Farbe',
      'confirm_delete': 'Wirklich löschen?',
      'connect': 'VERBINDEN',
      'connecting_classic': 'Sende Handshake (Broadcast)...',
      'connection_lost': 'Verbindung verloren zu',
      'controls': 'Steuerpult',
      'delete': 'Löschen',
      'departure': 'Abfahrt',
      'design_theme': 'Design (Dark Mode)',
      'diagnosis': 'Diagnose',
      'disconnect': 'TRENNEN',
      'display_always_on': 'Display immer an',
      'display_always_on_desc': 'Display bleibt nur dauerhaft an, solange mindestens eine Lok verbunden ist.',
      'edit': 'Bearbeiten',
      'export': 'Backup Export',
      'fanfare': 'Fanfare',
      'fuel': 'Tanken',
      'global_stop': 'GLOBAL STOPP',
      'halt': 'HALT',
      'handset_connected': 'Verbunden und aktiv',
      'handset_scanning': 'Suche nach Fernbedienung...',
      'handset_disconnected': 'Nicht verbunden',
      'handset_paired_success': 'Fernbedienung erfolgreich gekoppelt!',
      'hardware_and_setup': 'Hardware & Einrichtung',
      'horn': 'Hupe',
      'import': 'Backup Import',
      'info_no_mac_needed': 'Keine MAC benötigt',
      'invert': 'Invertieren',
      'key': 'Taste',
      'label_change_photo': 'Bild antippen zum Ändern',
      'label_choose_protocol': 'Protokoll wählen',
      'label_mac': 'MAC-Adresse',
      'label_name': 'Name der Lok',
      'label_notes': 'Notizen',
      'label_photo': 'Foto wählen',
      'label_protocol': 'Protokoll',
      'label_protocol': 'Protokoll / Hub-Typ',
      'lang_changed': 'Sprache geändert',
      'light': 'Licht',
      'light_b': 'Licht B',
      'light_c': 'Licht C',
      'list': 'Lokliste',
      'mould_king_classic': 'Mould King Classic (4.0)',
      'mould_king_classic_desc': 'Broadcast-Steuerung für ältere 4.0 Hubs (Dino)',
      'msg_incomplete': 'Bitte Protokoll auswählen und ggf. MAC eintragen!',
      'msg_scan_error': 'Scan-Fehler',
      'new_action': 'Neue PFx-Action',
      'new_button': 'Neuer Button',
      'new_pfx_action': 'Neue PFx Aktion',
      'new_train': 'Neue Lok anlegen',
      'no_trains': 'Keine Loks vorhanden.\nNutze das \'+\' zum Anlegen.',
      'notes_header': 'INFOS & WARTUNG',
      'offline': 'GETRENNT',
      'online': 'VERBUNDEN',
      'panel_mode_gears': 'Fahrstufen',
      'panel_mode_manual': 'Manuell (+/-)',
      'panel_profile_1': 'Profil I (Solo)',
      'panel_profile_2': 'Profil II (Last)',
      'pfx_button_1': 'Roter Knopf Links', 
      'pfx_button_2': 'Roter Knopf Rechts', 
      'pfx_button_3': 'Linkes Rad hoch', 
      'pfx_button_4': 'Linkes Rad runter', 
      'pfx_button_5': 'Rechtes Rad hoch', 
      'pfx_button_6': 'Rechtes Rad runter', 
      'port_door': 'Tür (Wechsel-Polung)',
      'port_light': 'Licht',
      'port_light_dir': 'Licht (Richtungsabhängig)',
      'port_motor': 'Motor',
      'port_motor_inv': 'Motor (Invertiert)',
      'port_none': 'Nichts',
      'protocol_mk_classic': 'Mould King (Classic / Broadcast)',
      'protocol_mk_modern': 'Mould King (Modern / BLE)',
      'readme': 'Anleitung',
      'readme_error': 'Fehler: readme.txt konnte nicht geladen werden.',
      'scan_not_required': 'Broadcast-Modus: Für diesen Hub ist kein Scan oder Koppeln nötig.',
      'scan_running': 'Suche läuft...',
      'select_train': 'Bitte wähle eine Lok aus der Liste aus',
      'settings': 'Einstellungen',
      'settings_bg_mode': 'Hosentaschen-Modus',
      'settings_bg_mode_desc': 'Steuerung bleibt bei gesperrtem Bildschirm aktiv. Verhindert Verbindungsabbrüche. (Verbraucht etwas mehr Akku)',
      'stop': 'NOTHALT',
      'stop_all': 'NOT-AUS',
      'tab_general': 'ALLGEMEIN',
      'tab_scan': 'SCAN',
      'tab_tuning': 'FEINABSTIMMUNG',
      'take_picture': 'Foto aufnehmen',
      'target': 'SOLL',
      'template_circuit_cube': 'Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_lego_duplo': 'Einfacher Antrieb (A), Licht & Sound intern',
      'template_lego_duplo': 'Duplo-Lok, ohne Ports.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_lego_hub': 'Standard-Belegung:\n• Port A: Antrieb\n• Port B: Licht/Motor\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_mould_king': 'Standard-Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\n• Port D: evt. 2. Antrieb (invertiert)\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_mould_king_classic': 'Standard-Belegung:\n• Port A: Antrieb\n• Port B/C: Licht (fahrtabhängig)\n• Port D: evt. 2. Antrieb (invertiert)\nVerbindung: Broadcast-Modus.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'template_mould_king_rwy_controller': 'FUNKTIONIERT NOCH NICHT\nNur Motor, kein Licht',
      'template_pybricks_hub': 'FUNKTIONIERT (NOCH) NICHT\nStandard-Belegung:\n• Port A: Antrieb\n• Port B: Licht/Motor\nVerbindung: BLE-Scan.\n\nTipp:\nHalte die Lok in der Liste lange gedrückt, um die Einstellungen und diesen Infokasten zu bearbeiten',
      'theme_dark': 'Dunkel',
      'theme_light': 'Hell',
      'theme_system': 'System',
      'tuning_acceleration': 'Beschleunigung',
      'tuning_auto_light': 'Automatisches Licht',
      'tuning_auto_light_help': 'Aktiviert das fahrtrichtungsabhängige Umpolen an Port B für BicolorLEDs',
      'tuning_brake': 'Bremskraft',
      'tuning_delta_step': 'Stufensprung (+/- Tasten)',
      'tuning_driving_behavior': 'FAHRVERHALTEN',
      'tuning_general_settings': 'Allgemeine Einstellungen',
      'tuning_hardware_title': 'Hardware und Ports',
      'tuning_hardware_subtitle': 'Weise jedem Anschluss der Akkubox eine Funktion zu.',
      'tuning_hardware_label': 'Beschriftung (z.B. Hupe)',
      'tuning_hardware_key': 'Welche Taste?',
      'tuning_hardware_channel': 'Welcher Kanal?',
      'tuning_invert_direction': 'Richtung invertieren',
      'tuning_invert_direction_help': 'Kehrt die Standard-Laufrichtung des Motors in der App um',
      'tuning_limits': 'Geschwindigkeitsgrenzen',
      'tuning_pfx_title': 'PFx-Action-Buttons',
      'tuning_pfx_subtitle': 'Lege eigene Knöpfe für Sounds und Lichter auf Kanal 2, 3 oder 4 an.',
      'tuning_profile_1': 'PROFIL I (Solo-Fahrt)',
      'tuning_profile_2': 'PROFIL II (Fahrt unter Last)',
      'tuning_ramp_delay': 'Trägheit [ms]',
      'tuning_ramping': 'Beschleunigungs-Rampe',
      'tuning_reverse': 'Rückwärts-Limit',
      'tuning_speed_levels': 'FAHRSTUFEN',
      "ui_auto_scale": "Automatische Skalierung",
      "ui_auto_scale_desc": "Passt die App-Größe automatisch an dein Display an.",
      "ui_scaling_manual": "Manuelle Skalierung",
      'unknown_device': 'Unbekanntes Gerät',
      'unknown_protocol': 'Unbekanntes Protokoll:',
      'vMax': 'Vmax (Höchstgeschwindigkeit)',
      'vMin': 'Vmin (Mindestgeschwindigkeit)',
      'workshop_add': 'NEUE LOK ANLEGEN',
      'workshop_edit': 'LOK EDITIEREN',
      'workshop_edit_save': 'SPEICHERN',



    },
    'en': {
      'about': 'About',
      'about_credits_text': 'Special thanks to J0EK3R (Ivan Murvai)\nfor reverse engineering the Mould King 4.0/6.0 protocol.',
      'about_credits_title': 'Credits & Acknowledgments:',
      'about_description': 'A free open-source project for brick enthusiasts.\n\n'
                        'Licensed under GNU GPL v3.\n\n'
                        'This project is not affiliated with, authorized, or endorsed by any of the mentioned manufacturers. All brand names are used solely for the purpose of describing technical compatibility and ensuring interoperability.\n\n'
                        'This software is provided "as-is" without any warranty or liability for damages to the hardware used (e.g., hubs, motors, remote controls).',      
      'about_github_btn': 'View Source on GitHub',
      'accessories': 'Accessories:',
      'actual': 'ACTUAL',
      'add': 'Add',
      'add_new_button': 'Add new button',
      'blockade': 'Wheel-Stopp',
      'brake': 'Brake',
      'btn_connect': 'Connect',
      'btn_disconnect': 'Disconnect',
      'btn_save': 'Save',
      'btn_start_scan': 'FIND HUBS',
      'buwizz_power_title': 'BuWizz Power Mode',
      'buwizz_power_subtitle': 'Takes effect only with a new connection.\nCaution: Higher voltages used at your own risk!',
      'buwizz_power_slow': 'Slow (approx. 5.2V)',
      'buwizz_power_normal': 'Normal (approx. 7.2V - Standard)',
      'buwizz_power_fast': 'Fast (approx. 9.2V)',
      'buwizz_power_ludicrous': 'Ludicrous (approx. 11.2V)',
      'buwizz_power_warning': 'Increased voltage can lead to overheating and destroy standard motors.',
      'cancel': 'Cancel',
      'channel': 'Channel',
      'choose_picture': 'Choose Picture',
      'color': 'Color',
      'confirm_delete': 'Confirm delete?',
      'connect': 'CONNECT',
      'connecting_classic': 'Sending Handshake (Broadcast)...',
      'connection_lost': 'Connection lost to',
      'controls': 'Control Panel',
      'delete': 'Delete',
      'departure': 'Departure',
      'design_theme': 'Design (Dark Mode)',
      'diagnosis': 'Diagnose',
      'disconnect': 'DISCONNECT SAFELY',
      'display_always_on': 'Keep Display On',
      'display_always_on_desc': 'Screen stays on only while at least one train is connected.',
      'edit': 'Edit',
      'export': 'Export Backup',
      'fanfare': 'Fanfare',
      'fuel': 'Fuel',
      'global_stop': 'GLOBAL STOP',
      'halt': 'HALT',
      'handset_connected': 'Connected and active',
      'handset_scanning': 'Searching for handset...',
      'handset_disconnected': 'Not connected',
      'handset_paired_success': 'Handset paired successfully',
      'hardware_and_setup': 'Hardware & Setup',
      'horn': 'Horn',
      'import': 'Import Backup',
      'info_no_mac_needed': 'No MAC needed',
      'invert': 'Invert',
      'key': 'Key',
      'label_change_photo': 'Tap image to change',
      'label_choose_protocol': 'Choose Protocol',
      'label_mac': 'MAC Address',
      'label_name': 'Train Name',
      'label_notes': 'Notes',
      'label_photo': 'Pick Photo',
      'label_protocol': 'Protocol',
      'label_protocol': 'Protocol / Hub Type',
      'lang_changed': 'Language changed',
      'light': 'Light',
      'light_b': 'Light B',
      'light_c': 'Light C',
      'list': 'Train List',
      'mould_king_classic': 'Mould King Classic (4.0)',
      'mould_king_classic_desc': 'Broadcast control for older 4.0 hubs (Dino)',
      'msg_incomplete': 'Please select protocol and enter MAC address if necessary!',
      'msg_scan_error': 'Scan error',
      'new_action': 'New PFx Action',
      'new_button': 'New Button',
      'new_pfx_action': 'New PFx Action',
      'new_train': 'Add New Train',
      'no_trains': 'No trains available.\nUse \'+\' to create one.',
      'notes_header': 'INFO & MAINTENANCE',
      'offline': 'OFFLINE',
      'online': 'ONLINE',
      'panel_mode_gears': 'Gears',
      'panel_mode_manual': 'Manual (+/-)',
      'panel_profile_1': 'Profile I (Solo)',
      'panel_profile_2': 'Profile II (Load)',
      'pfx_button_1': 'Red Button Left', 
      'pfx_button_2': 'Red Button Right', 
      'pfx_button_3': 'Left Dial Up', 
      'pfx_button_4': 'Left Dial Down', 
      'pfx_button_5': 'Right Dial Up', 
      'pfx_button_6': 'Right Dial Down',
      'port_door': 'Door (Polarity Switch)',
      'port_light': 'Light',
      'port_light_dir': 'Light (Directional)',
      'port_motor': 'Motor',
      'port_motor_inv': 'Motor (Inverted)',
      'port_none': 'None',
      'protocol_mk_classic': 'Mould King (Classic / Broadcast)',
      'protocol_mk_modern': 'Mould King (Modern / BLE)',
      'readme': 'Manual',
      'scan_not_required': 'Broadcast Mode: No scan or pairing required for this hub.',
      'scan_running': 'Scanning...',
      'select_train': 'Please select a train from the list',
      'settings': 'Settings',
      'settings_bg_mode': 'Pocket Mode',
      'settings_bg_mode_desc': 'Control remains active when the screen is locked. Prevents connection drops. (Uses more battery)',
      'stop': 'STOP',
      'stop_all': 'Emergency Stop',
      'tab_general': 'GENERAL',
      'tab_scan': 'SCAN',
      'tab_tuning': 'TUNING',
      'take_picture': 'Take Picture',
      'target': 'TARGET',
      'template_circuit_cube': 'Assignment:\n• Port A: Drive\n• Port B/C: Light (Auto-Light)\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_lego_duplo': 'Simple drive (A), internal light & sound',
      'template_lego_hub': 'Standard Assignment:\n• Port A: Drive\n• Port B: Light/Drive\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_mould_king': 'Standard Assignment:\n• Port A: Drive\n• Port B/C: Light (Auto-Light)\n• Port D: poss. 2nd Drive (inverted)\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_mould_king_classic': 'Standard Assignment:\n• Port A: Drive\n• Port B/C: Licht (Auto-Light)\n• Port D: evt. 2. Antrieb (invertiert)\nConnection: Broadcast.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'template_mould_king_rwy_controller': 'CURRENTLY NOT WORKING\nOnly motor, no light',
      'template_pybricks_hub': 'CURRENTLY NOT WORKING\nStandard Assignment:\n• Port A: Drive\n• Port B: Light/Drive\nConnection: BLE-Scan.\n\nTip: Press and hold the locomotive in the list to edit the settings and this info box.',
      'theme_dark': 'dark',
      'theme_light': 'light',
      'theme_system': 'System',
      'tuning_acceleration': 'Acceleration',
      'tuning_auto_light': 'Automatic Light',
      'tuning_auto_light_help': 'Activates the direction-dependent polarity reversal at Port B for bicolor LEDs',
      'tuning_brake': 'Braking Force',
      'tuning_delta_step': 'Step Size (+/- Buttons)',
      'tuning_driving_behavior': 'DRIVING BEHAVIOR',
      'tuning_general_settings': 'General Settings',
      'tuning_hardware_title': 'Hardware & Ports',
      'tuning_hardware_subtitle': 'Assign a function to each port of the battery box.',
      'tuning_hardware_label': 'Label (e.g., Horn)',
      'tuning_hardware_key': 'Which button?',
      'tuning_hardware_channel': 'Which channel?',
      'tuning_limits': 'Speed Limits',
      'tuning_pfx_title': 'PFx Action Buttons',
      'tuning_pfx_subtitle': 'Create custom buttons for sounds and lights on channel 2, 3, or 4.',
      'tuning_profile_1': 'PROFILE I (Solo-Drive)',
      'tuning_profile_2': 'PROFILE II (Under Load)',
      'tuning_ramp_delay': 'Inertia [ms]',
      'tuning_ramping': 'Acceleration Ramp',
      'tuning_reverse': 'Max Reverse Limit',
      'tuning_speed_levels': 'Speed Levels (Presets)',
      "ui_auto_scale": "Auto-Scaling",
      "ui_auto_scale_desc": "Automatically adjusts the app size to fit your screen.",
      "ui_scaling_manual": "Manual Scaling",
      'unknown_device': 'Unknown Device',
      'unknown_protocol': 'Unknown Protocol:',
      'vMax': 'Vmax (Maximum Speed)',
      'vMin': 'Vmin (Minimum Speed)',
      'workshop_add': 'ADD NEW TRAIN',
      'workshop_edit': 'EDIT TRAIN',
      'workshop_edit_save': 'Save',

    }
  };

  static String tr(String key) {
    return _values[lang]?[key] ?? key;
  }
}

extension Loc on String {
  String get tr => L10n.tr(this);
}